### ISSUE TITLE
Too long rule name

### ISSUE THREAD

**Issue by fliespl** [zabojcaspamu/spamassassin_rules#14]
Daily updates produce such warnings. Might be good idea to rename rule to something more compact.

/etc/cron.daily/spamassassin:
Apr 14 08:33:47.632 [5167] warn: config: warning: rule name 'ZABOJCASPAMU_SPAMWARE_XMAILER_GOOD_Mailer' is over 40 chars (recommended maximum length is 22 characters)
Apr 14 08:33:48.545 [5167] warn: lint: 1 issues detected, please rerun with debug enabled for more information

**Comment by takenek** [comment]
Same problem here.

**Comment by zabojcaspamu** [comment]
Fix.
